version: "2"
services:
  server:
    environment:
     - ENVIRONMENT=test
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html

  test:
    image: phpunit/phpunit:6.0.6
    volumes:
      - .:/app
    working_dir: /app
    links:
      - server
    command: "-c ./Test/phpunit.xml --testdox"
